# Generated by Django 5.2.8 on 2026-01-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                ("active_users", models.IntegerField(default=0)),
                ("new_users", models.IntegerField(default=0)),
                ("total_users", models.IntegerField(default=0)),
                ("new_sessions", models.IntegerField(default=0)),
                ("completed_sessions", models.IntegerField(default=0)),
                ("total_screenshots", models.IntegerField(default=0)),
                ("total_changes_detected", models.IntegerField(default=0)),
                ("total_odds_captured", models.IntegerField(default=0)),
                ("avg_session_duration", models.FloatField(default=0.0)),
                ("avg_screenshot_quality", models.FloatField(default=0.0)),
                ("system_uptime", models.FloatField(default=100.0)),
                ("top_monitored_sites", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "betvision_daily_stats",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PlatformMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_registered_users", models.IntegerField(default=0)),
                ("active_users_today", models.IntegerField(default=0)),
                ("active_users_week", models.IntegerField(default=0)),
                ("active_users_month", models.IntegerField(default=0)),
                ("free_users", models.IntegerField(default=0)),
                ("pro_users", models.IntegerField(default=0)),
                ("enterprise_users", models.IntegerField(default=0)),
                ("total_monitoring_sessions", models.IntegerField(default=0)),
                ("total_screenshots_captured", models.IntegerField(default=0)),
                ("total_changes_detected", models.IntegerField(default=0)),
                ("total_monitoring_hours", models.FloatField(default=0.0)),
                ("avg_screenshot_quality", models.FloatField(default=0.0)),
                ("system_uptime_percentage", models.FloatField(default=100.0)),
                ("avg_response_time", models.FloatField(default=0.0)),
                ("most_monitored_sites", models.JSONField(blank=True, default=list)),
                ("peak_usage_hours", models.JSONField(blank=True, default=list)),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "betvision_platform_metrics",
            },
        ),
        migrations.CreateModel(
            name="SiteAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField(unique=True)),
                ("site_name", models.CharField(blank=True, max_length=255)),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_users", models.IntegerField(default=0)),
                ("total_screenshots", models.IntegerField(default=0)),
                ("total_monitoring_hours", models.FloatField(default=0.0)),
                ("avg_screenshot_quality", models.FloatField(default=0.0)),
                ("avg_odds_per_screenshot", models.FloatField(default=0.0)),
                ("avg_changes_per_hour", models.FloatField(default=0.0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("most_used_interval", models.IntegerField(default=30)),
                ("most_used_quality", models.CharField(default="high", max_length=20)),
                ("first_monitored", models.DateTimeField(blank=True, null=True)),
                ("last_monitored", models.DateTimeField(blank=True, null=True)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "betvision_site_analytics",
                "ordering": ["-total_sessions"],
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_sessions", models.IntegerField(default=0)),
                ("total_screenshots", models.IntegerField(default=0)),
                ("total_monitoring_hours", models.FloatField(default=0.0)),
                ("total_changes_detected", models.IntegerField(default=0)),
                ("total_odds_captured", models.IntegerField(default=0)),
                ("avg_session_duration", models.FloatField(default=0.0)),
                ("avg_screenshots_per_session", models.FloatField(default=0.0)),
                ("avg_changes_per_session", models.FloatField(default=0.0)),
                ("most_monitored_site", models.URLField(blank=True)),
                ("most_used_interval", models.IntegerField(default=30)),
                ("preferred_quality", models.CharField(default="high", max_length=20)),
                ("most_active_hour", models.IntegerField(blank=True, null=True)),
                ("most_active_day", models.IntegerField(blank=True, null=True)),
                ("last_calculated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "betvision_user_analytics",
            },
        ),
    ]
