# Generated by Django 5.2.8 on 2026-01-08 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MonitoringSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_url", models.URLField()),
                ("site_name", models.CharField(blank=True, max_length=255)),
                ("session_name", models.CharField(blank=True, max_length=255)),
                ("monitoring_interval", models.IntegerField(default=30)),
                ("max_duration", models.IntegerField(default=60)),
                (
                    "screenshot_quality",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("high", "High"),
                            ("ultra", "Ultra"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("last_screenshot_time", models.DateTimeField(blank=True, null=True)),
                ("screenshots_count", models.IntegerField(default=0)),
                ("changes_detected", models.IntegerField(default=0)),
                ("odds_captured", models.IntegerField(default=0)),
                ("errors_count", models.IntegerField(default=0)),
                ("focus_areas", models.JSONField(blank=True, default=list)),
                ("alert_keywords", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "betvision_monitoring_sessions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Screenshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="screenshots/%Y/%m/%d/")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="thumbnails/%Y/%m/%d/"
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_size", models.IntegerField()),
                (
                    "quality",
                    models.CharField(
                        choices=[
                            ("poor", "Poor"),
                            ("good", "Good"),
                            ("excellent", "Excellent"),
                        ],
                        default="good",
                        max_length=20,
                    ),
                ),
                ("width", models.IntegerField()),
                ("height", models.IntegerField()),
                ("odds_detected", models.IntegerField(default=0)),
                ("live_matches_detected", models.IntegerField(default=0)),
                ("page_elements_count", models.IntegerField(default=0)),
                ("page_load_success", models.BooleanField(default=True)),
                ("extracted_text", models.TextField(blank=True)),
                ("detected_odds", models.JSONField(blank=True, default=dict)),
                ("live_indicators", models.JSONField(blank=True, default=dict)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="screenshots",
                        to="monitoring.monitoringsession",
                    ),
                ),
            ],
            options={
                "db_table": "betvision_screenshots",
                "ordering": ["-captured_at"],
            },
        ),
        migrations.CreateModel(
            name="OddsData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "odds_type",
                    models.CharField(
                        choices=[
                            ("decimal", "Decimal"),
                            ("fractional", "Fractional"),
                            ("american_plus", "American (+)"),
                            ("american_minus", "American (-)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("odds_value", models.CharField(max_length=50)),
                ("match_info", models.CharField(blank=True, max_length=255)),
                ("bet_type", models.CharField(blank=True, max_length=100)),
                ("position_x", models.IntegerField(blank=True, null=True)),
                ("position_y", models.IntegerField(blank=True, null=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds_data",
                        to="monitoring.monitoringsession",
                    ),
                ),
                (
                    "screenshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="odds_data",
                        to="monitoring.screenshot",
                    ),
                ),
            ],
            options={
                "db_table": "betvision_odds_data",
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="MonitoringAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("odds_change", "Odds Change"),
                            ("new_match", "New Match"),
                            ("keyword_detected", "Keyword Detected"),
                            ("error", "Error"),
                            ("threshold_reached", "Threshold Reached"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("trigger_data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_dismissed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monitoring_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.monitoringsession",
                    ),
                ),
                (
                    "related_screenshot",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="monitoring.screenshot",
                    ),
                ),
            ],
            options={
                "db_table": "betvision_monitoring_alerts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChangeDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("visual", "Visual Change"),
                            ("odds", "Odds Change"),
                            ("content", "Content Change"),
                            ("layout", "Layout Change"),
                        ],
                        default="visual",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("change_percentage", models.FloatField()),
                ("description", models.TextField()),
                ("affected_areas", models.JSONField(blank=True, default=list)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes",
                        to="monitoring.monitoringsession",
                    ),
                ),
                (
                    "current_screenshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes_as_current",
                        to="monitoring.screenshot",
                    ),
                ),
                (
                    "previous_screenshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changes_as_previous",
                        to="monitoring.screenshot",
                    ),
                ),
            ],
            options={
                "db_table": "betvision_change_detections",
                "ordering": ["-detected_at"],
            },
        ),
    ]
